import type { SkillDef, SpellingSkillTag } from "./types";

export const SPELLING_SKILLS: SkillDef[] = [
  { tag: "cvc_short_a", domain: "spelling", name: "Short 'a' CVC", difficulty: 1, description: "cat, map, bag." },
  { tag: "cvc_short_e", domain: "spelling", name: "Short 'e' CVC", difficulty: 1, description: "bed, net, pen." },
  { tag: "cvc_short_i", domain: "spelling", name: "Short 'i' CVC", difficulty: 1, description: "sit, pig, big." },
  { tag: "cvc_short_o", domain: "spelling", name: "Short 'o' CVC", difficulty: 1, description: "dog, pot, hop." },
  { tag: "cvc_short_u", domain: "spelling", name: "Short 'u' CVC", difficulty: 1, description: "cup, bug, run." },
  { tag: "digraphs_sh_ch_th", domain: "spelling", name: "Digraphs sh/ch/th", difficulty: 2, description: "ship, chip, thin." },
  { tag: "long_a_cvce", domain: "spelling", name: "Long 'a' silent-e", difficulty: 3, description: "cake, name, lake." },
  { tag: "long_i_cvce", domain: "spelling", name: "Long 'i' silent-e", difficulty: 3, description: "bike, ride, time." },
  { tag: "long_o_cvce", domain: "spelling", name: "Long 'o' silent-e", difficulty: 3, description: "rope, home, note." },
  { tag: "r_controlled_ar_or", domain: "spelling", name: "R-controlled ar/or", difficulty: 4, description: "car, star, for, corn." },
  { tag: "vowel_teams_ee_ea", domain: "spelling", name: "Vowel teams ee/ea", difficulty: 4, description: "tree, bead, read." },
  { tag: "ie_vs_ei", domain: "spelling", name: "'ie' vs 'ei'", difficulty: 6, description: "believe, receive, field." },
  { tag: "silent_letters", domain: "spelling", name: "Silent letters", difficulty: 5, description: "knee, knock, lamb, write." },
  { tag: "common_sight_words", domain: "spelling", name: "High-frequency sight words", difficulty: 2, description: "because, friend, said." },
];

/**
 * Curated word banks. These are classic phonics-pattern and sight-word
 * sets (Dolch/Fry style) rather than AI-generated to keep content
 * predictable and age-appropriate.
 */
export const SPELLING_WORDS: Record<SpellingSkillTag, string[]> = {
  cvc_short_a: [
    "cat", "bag", "map", "hat", "tap", "ran", "sad", "fan", "pan", "jam",
    "rat", "mat", "bat", "nap", "lap", "had", "dad", "ham", "wag", "tag",
    "gas", "yam", "van", "cab", "cap", "fat", "pat", "rag", "tan", "sat",
  ],
  cvc_short_e: [
    "bed", "net", "pen", "ten", "leg", "red", "pet", "egg", "hen", "web",
    "vet", "wet", "yes", "yet", "jet", "let", "set", "men", "fed", "led",
    "beg", "den", "elf", "end", "get", "met", "nest", "best", "less", "step",
  ],
  cvc_short_i: [
    "sit", "pig", "big", "pin", "lid", "hit", "dig", "rip", "tin", "win",
    "fin", "fix", "kid", "lip", "lit", "mix", "nip", "rib", "sip", "wig",
    "zip", "him", "his", "dim", "did", "fit", "kit", "bib", "milk", "wish",
  ],
  cvc_short_o: [
    "dog", "pot", "hop", "log", "mop", "fox", "box", "top", "hot", "job",
    "got", "hog", "jog", "mom", "nod", "not", "pop", "rod", "sob", "ox",
    "cot", "dot", "lot", "rob", "rot", "fog", "frog", "stop", "drop", "rock",
  ],
  cvc_short_u: [
    "cup", "bug", "run", "sun", "fun", "nut", "hut", "mud", "bun", "tub",
    "bus", "but", "cub", "dug", "gum", "hug", "hum", "jug", "mug", "yum",
    "pup", "rub", "rug", "tug", "us", "up", "duck", "must", "junk", "drum",
  ],
  digraphs_sh_ch_th: [
    "ship", "shop", "chip", "chin", "thin", "that", "dish", "fish", "rich", "with",
    "shed", "shut", "shell", "shin", "rush", "wish", "cash",
    "chat", "chest", "chick", "child", "much", "such", "lunch", "bench",
    "thick", "this", "then", "them", "moth", "path", "math",
  ],
  long_a_cvce: [
    "cake", "name", "lake", "gate", "made", "game", "face", "take", "wave", "plate",
    "bake", "save", "tape", "race", "page", "cane", "cape", "mane", "vase", "place",
    "snake", "skate", "shade", "grape", "frame", "shape", "stage", "blade", "brave", "trade",
  ],
  long_i_cvce: [
    "bike", "ride", "time", "kite", "mine", "hide", "fine", "side", "bite", "smile",
    "dive", "five", "hive", "like", "line", "pile", "pine", "ripe", "size", "wide",
    "while", "white", "write", "slide", "spike", "stripe", "shine", "drive", "prize", "tribe",
  ],
  long_o_cvce: [
    "rope", "home", "note", "hope", "bone", "stone", "hole", "joke", "rode", "woke",
    "code", "dome", "cone", "dose", "hose", "mole", "nose", "pole", "rose", "vote",
    "smoke", "spoke", "globe", "broke", "stole", "wrote", "alone", "drove", "stove", "phone",
  ],
  r_controlled_ar_or: [
    "car", "star", "farm", "park", "for", "corn", "storm", "short", "fork", "horn",
    "arm", "art", "bar", "card", "cart", "dark", "harm", "hard", "jar", "yard",
    "born", "cord", "fort", "north", "porch", "sort", "sport", "torch", "more", "store",
  ],
  vowel_teams_ee_ea: [
    "tree", "bead", "read", "seed", "meet", "team", "seat", "beach", "sleep", "dream",
    "bee", "feet", "free", "knee", "queen", "speed", "sweet", "wheel", "green", "sheep",
    "each", "easy", "leaf", "mean", "neat", "peach", "reach", "sea", "speak", "teach",
  ],
  ie_vs_ei: [
    "believe", "receive", "field", "piece", "ceiling", "friend", "niece", "neighbor", "thief", "weight",
    "achieve", "brief", "chief", "grief", "priest", "shield", "tier", "yield", "diesel", "hygiene",
    "either", "neither", "perceive", "deceive", "seize", "vein", "rein", "freight", "eight", "their",
  ],
  silent_letters: [
    "knee", "knock", "lamb", "write", "wrist", "climb", "thumb", "know", "knight", "ghost",
    "knife", "knit", "knot", "knew", "comb", "crumb", "numb", "tomb",
    "wrap", "wreck", "wren", "wrong", "honest", "hour", "answer", "island", "listen", "sword",
    "scene", "sign",
  ],
  common_sight_words: [
    "because", "friend", "said", "could", "would", "every", "school", "people", "their", "through",
    "again", "always", "another", "around", "before", "between", "where", "above", "should", "great",
    "right", "thought", "together", "today", "until", "water", "world", "young", "answer", "enough",
  ],
};

/**
 * Per-word sentences for spelling_audio items ("use in a sentence"), so
 * each word lands in a context that actually makes sense. Kept short
 * and kid-friendly (~6-year-old reading level).
 */
export const SPELLING_SENTENCES: Record<string, string> = {
  // cvc_short_a
  cat: "The cat sat on my lap.",
  bag: "My bag is full of books.",
  map: "We looked at the map.",
  hat: "He put on a warm hat.",
  tap: "Turn off the tap.",
  ran: "The dog ran home fast.",
  sad: "She felt sad today.",
  fan: "The fan is loud.",
  pan: "Mom flipped the pan.",
  jam: "I like jam on toast.",
  // cvc_short_e
  bed: "Time to go to bed.",
  net: "The fish jumped in the net.",
  pen: "Can I borrow your pen?",
  ten: "I can count to ten.",
  leg: "He hurt his leg.",
  red: "She wore a red dress.",
  pet: "My pet is a cat.",
  egg: "I ate one egg.",
  hen: "The hen laid an egg.",
  web: "A spider spun a web.",
  // cvc_short_i
  sit: "Please sit down.",
  pig: "The pig is pink.",
  big: "That's a big truck!",
  pin: "Don't touch the pin.",
  lid: "Put the lid on the jar.",
  hit: "He hit the ball hard.",
  dig: "Let's dig in the sand.",
  rip: "Try not to rip the paper.",
  tin: "I found a tin of beans.",
  win: "I hope we win the game!",
  // cvc_short_o
  dog: "My dog likes to play.",
  pot: "The pot is hot.",
  hop: "Frogs can hop far.",
  log: "A log fell off the pile.",
  mop: "She used a mop to clean.",
  fox: "The fox ran into the woods.",
  box: "What's inside the box?",
  top: "The toy is on top.",
  hot: "The soup is too hot.",
  job: "Dad has a new job.",
  // cvc_short_u
  cup: "My cup is full of milk.",
  bug: "A bug flew past me.",
  run: "I like to run fast.",
  sun: "The sun is bright today.",
  fun: "We had so much fun!",
  nut: "A squirrel ate the nut.",
  hut: "We built a hut of sticks.",
  mud: "My boots are full of mud.",
  bun: "I had a bun for lunch.",
  tub: "The baby splashed in the tub.",
  // digraphs sh/ch/th
  ship: "A big ship sailed past.",
  shop: "We went to the toy shop.",
  chip: "I ate one chip.",
  chin: "She has a dimple on her chin.",
  thin: "The ice is too thin to walk on.",
  that: "That is my favorite book.",
  dish: "Please put your dish in the sink.",
  fish: "The fish is swimming.",
  rich: "A king is rich.",
  with: "I played with my friend.",
  // long_a CVCe
  cake: "We ate a chocolate cake.",
  name: "What is your name?",
  lake: "The lake was cold.",
  gate: "She opened the gate.",
  made: "I made a card for you.",
  game: "Let's play a game!",
  face: "Her face lit up.",
  take: "Take one more cookie.",
  wave: "I saw a big wave.",
  plate: "My plate is empty.",
  // long_i CVCe
  bike: "I can ride my bike.",
  ride: "Let's go for a ride.",
  time: "What time is it?",
  kite: "His kite is in the tree.",
  mine: "That toy is mine.",
  hide: "Let's hide under the bed.",
  fine: "I feel fine today.",
  side: "Sit on this side.",
  bite: "Take a small bite.",
  smile: "Your smile makes me happy.",
  // long_o CVCe
  rope: "She pulled on the rope.",
  home: "I walked home.",
  note: "I wrote you a note.",
  hope: "I hope you have fun.",
  bone: "The dog chewed a bone.",
  stone: "He kicked a stone.",
  hole: "A hole in my sock!",
  joke: "Tell me a funny joke.",
  rode: "We rode our bikes to school.",
  woke: "I woke up early.",
  // r-controlled ar/or
  car: "Dad drives a blue car.",
  star: "A bright star is in the sky.",
  farm: "My aunt lives on a farm.",
  park: "Let's go to the park.",
  for: "This is for you.",
  corn: "I ate corn on the cob.",
  storm: "A big storm is coming.",
  short: "He wore short pants.",
  fork: "Eat with a fork, please.",
  horn: "The car horn is loud.",
  // vowel teams ee/ea
  tree: "A bird sat in the tree.",
  bead: "She made a bead necklace.",
  read: "I love to read at night.",
  seed: "Plant the seed in the dirt.",
  meet: "Let's meet at the door.",
  team: "Our team won the game.",
  seat: "This is my seat.",
  beach: "We built a castle on the beach.",
  sleep: "Time to sleep.",
  dream: "I had a silly dream.",
  // ie vs ei
  believe: "I believe you can do it.",
  receive: "Did you receive the letter?",
  field: "We played in the field.",
  piece: "Have a piece of apple.",
  ceiling: "A spider is on the ceiling.",
  friend: "She is my best friend.",
  niece: "My niece is four years old.",
  neighbor: "Our neighbor waved hi.",
  thief: "The thief got caught.",
  weight: "Check the weight of the bag.",
  // silent letters
  knee: "I scraped my knee.",
  knock: "Knock before you come in.",
  lamb: "The lamb is soft.",
  write: "Please write your name.",
  wrist: "My wrist hurts a little.",
  climb: "They climb the tall tree.",
  thumb: "He hurt his thumb.",
  know: "I know the answer!",
  knight: "The knight had a shiny sword.",
  ghost: "The ghost went whoo.",
  // common sight words
  because: "I laughed because it was funny.",
  said: "She said hello to me.",
  could: "Could you help me?",
  would: "I would like some milk.",
  every: "Every day is a new start.",
  school: "We walk to school together.",
  people: "A lot of people were there.",
  their: "They put on their coats.",
  through: "We walked through the park.",

  // --- Expanded word bank below (added 2026-04). Sentences kept short
  // and concrete so kids can picture them. ---

  // cvc_short_a additions
  rat: "A rat is in the barn.",
  mat: "Wipe your feet on the mat.",
  bat: "He swung the bat hard.",
  nap: "The baby took a nap.",
  lap: "The cat sat in my lap.",
  had: "I had two cookies.",
  dad: "My dad makes pancakes.",
  ham: "She put ham on the bread.",
  wag: "Dogs wag their tails.",
  tag: "Let's play tag at recess.",
  gas: "The car needs more gas.",
  yam: "We baked a sweet yam.",
  van: "The blue van is ours.",
  cab: "We took a cab to the park.",
  cap: "He wears a red cap.",
  fat: "The cat is a bit fat.",
  pat: "I gave the dog a pat.",
  rag: "Use a rag to clean it.",
  tan: "Her shoes are tan.",
  sat: "I sat on the bench.",

  // cvc_short_e additions
  vet: "The vet helped my puppy.",
  wet: "My socks are wet.",
  yes: "I said yes to the snack.",
  yet: "Are we there yet?",
  jet: "The jet flew up high.",
  let: "Please let me try.",
  set: "Set the cup on the table.",
  men: "Two men fixed the road.",
  fed: "I fed the fish.",
  led: "She led us to our seats.",
  beg: "The dog will beg for treats.",
  den: "A fox lives in the den.",
  elf: "The elf hid the gift.",
  end: "We made it to the end.",
  get: "Can you get the door?",
  met: "We met at the park.",
  nest: "A bird's nest is in the tree.",
  best: "You did your best!",
  less: "I want less sugar.",
  step: "Watch your step here.",

  // cvc_short_i additions
  fin: "The fish has a long fin.",
  fix: "Dad will fix the bike.",
  kid: "Every kid got a sticker.",
  lip: "I bit my lip.",
  lit: "The candle is lit.",
  mix: "Mix the eggs and flour.",
  nip: "It's a chilly nip outside.",
  rib: "I poked his rib gently.",
  sip: "Take a sip of water.",
  wig: "The clown wore a wig.",
  zip: "Zip up your coat!",
  him: "I gave him a hug.",
  his: "That book is his.",
  dim: "The light is too dim.",
  did: "Look what I did!",
  fit: "These shoes fit just right.",
  kit: "I got a new craft kit.",
  bib: "The baby wore a bib.",
  milk: "Pour some milk, please.",
  wish: "Make a wish on the candle.",

  // cvc_short_o additions
  got: "I got a new bike.",
  hog: "The hog rolled in the mud.",
  jog: "Let's jog around the block.",
  mom: "My mom is so funny.",
  nod: "He gave a small nod.",
  not: "I am not tired yet.",
  pop: "I love grape soda pop.",
  rod: "She fished with a long rod.",
  sob: "Don't sob — it'll be okay.",
  ox: "The big ox pulled the cart.",
  cot: "We slept on a cot.",
  dot: "Put a dot on the i.",
  lot: "There's a lot to do.",
  rob: "It's wrong to rob from others.",
  rot: "Old apples will rot.",
  fog: "The fog hid the hills.",
  frog: "A frog hopped in the pond.",
  stop: "Cars stop at the red light.",
  drop: "Don't drop the egg!",
  rock: "I found a smooth rock.",

  // cvc_short_u additions
  bus: "We took the school bus.",
  but: "I want one, but only one.",
  cub: "The bear cub is small.",
  dug: "We dug a deep hole.",
  gum: "He chews lots of gum.",
  hug: "I gave my mom a hug.",
  hum: "She likes to hum songs.",
  jug: "Pour the milk from the jug.",
  mug: "My mug has a frog on it.",
  yum: "Yum, this cake is good!",
  pup: "The pup is so cute.",
  rub: "Rub the spot to clean it.",
  rug: "The cat naps on the rug.",
  tug: "Give the rope a tug.",
  us: "Come with us!",
  up: "The kite went up high.",
  duck: "A duck swam by.",
  must: "I must finish my work.",
  junk: "Toss the junk in the bin.",
  drum: "He plays a loud drum.",

  // digraphs sh/ch/th additions
  shed: "Tools are in the shed.",
  shut: "Please shut the door.",
  shell: "I found a shell on the sand.",
  shin: "I bumped my shin.",
  rush: "We had to rush to the bus.",
  cash: "Pay with cash or card.",
  chat: "Let's chat after lunch.",
  chest: "The treasure was in the chest.",
  chick: "A baby chick says peep.",
  child: "Each child got a balloon.",
  much: "Thank you so much!",
  such: "It was such a fun day.",
  lunch: "We ate lunch at noon.",
  bench: "He sat on the bench.",
  thick: "The book is very thick.",
  this: "Try this snack first.",
  then: "First we eat, then we play.",
  them: "Give them to me, please.",
  moth: "A moth flew to the lamp.",
  path: "Follow the dirt path.",
  math: "Math class is in the morning.",

  // long_a CVCe additions
  bake: "We bake muffins on Sundays.",
  save: "I save my pennies.",
  tape: "Tape this to the wall.",
  race: "We had a race to the door.",
  page: "Turn to the next page.",
  cane: "Grandpa walks with a cane.",
  cape: "The hero wore a red cape.",
  mane: "The lion has a fluffy mane.",
  vase: "Roses sit in the vase.",
  place: "Save my place at the table.",
  snake: "The snake slid through the grass.",
  skate: "I learned to skate today.",
  shade: "Let's sit in the shade.",
  grape: "I ate a juicy grape.",
  frame: "Put the photo in a frame.",
  shape: "What shape is the moon?",
  stage: "She sang on the stage.",
  blade: "The blade is very sharp.",
  brave: "You were so brave!",
  trade: "Want to trade snacks?",

  // long_i CVCe additions
  dive: "I love to dive in the pool.",
  five: "I am five years old today.",
  hive: "Bees live in the hive.",
  like: "I like ice cream.",
  line: "Stand in a straight line.",
  pile: "She made a pile of leaves.",
  pine: "A tall pine tree fell.",
  ripe: "The banana is ripe.",
  size: "What size shirt do you wear?",
  wide: "Open your mouth wide.",
  while: "Wait here for a while.",
  white: "Snow is cold and white.",
  slide: "The slide is so fast!",
  spike: "There's a spike on the fence.",
  stripe: "Tigers have a black stripe.",
  shine: "Let your light shine!",
  drive: "Mom can drive a truck.",
  prize: "She won the top prize.",
  tribe: "The tribe shared a meal.",

  // long_o CVCe additions
  code: "I cracked the secret code.",
  dome: "The dome is made of glass.",
  cone: "Want a vanilla cone?",
  dose: "Take one dose at bedtime.",
  hose: "Spray the plants with the hose.",
  mole: "A mole dug up the yard.",
  nose: "She wrinkled her nose.",
  pole: "The flag is on a tall pole.",
  rose: "He gave her a red rose.",
  vote: "Class vote: pizza or tacos?",
  smoke: "Smoke went up the chimney.",
  spoke: "She spoke up in class.",
  globe: "Spin the globe and pick a place.",
  broke: "I broke my pencil tip.",
  stole: "The fox stole the cheese.",
  wrote: "I wrote you a card.",
  alone: "She walked home alone.",
  drove: "Dad drove us to school.",
  stove: "The pot is hot on the stove.",
  phone: "Please answer the phone.",

  // r-controlled ar/or additions
  arm: "I broke my arm last year.",
  art: "Art class is on Tuesdays.",
  bar: "He grabbed a granola bar.",
  card: "I made a card for grandma.",
  cart: "Push the cart to the car.",
  dark: "It is dark outside.",
  harm: "We mean no harm.",
  hard: "The puzzle is hard.",
  jar: "Cookies are in the jar.",
  yard: "Run around the yard!",
  born: "When were you born?",
  cord: "Don't trip on the cord.",
  fort: "We built a pillow fort.",
  north: "Birds fly north in spring.",
  porch: "Sit with me on the porch.",
  sort: "Help sort the clean socks.",
  sport: "What's your favorite sport?",
  torch: "He held up the torch.",
  more: "May I have more milk?",
  store: "We shop at the corner store.",

  // vowel teams ee/ea additions
  bee: "A bee buzzed by my ear.",
  feet: "My feet hurt from running.",
  free: "These cookies are free!",
  queen: "The queen wore a crown.",
  speed: "The car had a lot of speed.",
  sweet: "This apple is so sweet.",
  wheel: "One wheel fell off the cart.",
  green: "Grass is green in summer.",
  sheep: "The sheep ate the grass.",
  each: "Take one each.",
  easy: "That puzzle was easy.",
  leaf: "A red leaf fell down.",
  mean: "Don't be mean to your sister.",
  neat: "Your room looks neat.",
  peach: "The peach is fuzzy.",
  reach: "I can reach the top shelf.",
  sea: "Waves crash on the sea.",
  speak: "Please speak up.",
  teach: "She will teach us to draw.",

  // ie/ei additions
  achieve: "You can achieve your goal.",
  brief: "We had a brief talk.",
  chief: "He is the fire chief.",
  grief: "She felt grief when her dog died.",
  priest: "The priest waved hello.",
  shield: "The knight raised his shield.",
  tier: "The cake had a top tier.",
  yield: "Cars must yield at the sign.",
  diesel: "Big trucks use diesel fuel.",
  hygiene: "Brush your teeth for good hygiene.",
  either: "Either pick is fine.",
  neither: "Neither shoe fits me.",
  perceive: "I can perceive the soft sound.",
  deceive: "It's wrong to deceive a friend.",
  seize: "Seize the chance to learn.",
  vein: "I see a tiny vein on my hand.",
  rein: "Hold the horse's rein.",
  freight: "The freight train is long.",
  eight: "I am eight years old.",

  // silent letters additions
  knife: "Use a knife to cut bread.",
  knit: "Grandma will knit a scarf.",
  knot: "Tie a knot in the rope.",
  knew: "I knew the answer!",
  comb: "I lost my hair comb.",
  crumb: "A crumb fell on the floor.",
  numb: "My fingers feel numb in the cold.",
  tomb: "The old tomb was cold inside.",
  wrap: "Wrap the gift in paper.",
  wreck: "The car had a small wreck.",
  wren: "A tiny wren sang outside.",
  wrong: "Sorry, I was wrong.",
  honest: "Be honest with me.",
  hour: "We waited an hour.",
  answer: "Do you know the answer?",
  island: "We sailed to the island.",
  listen: "Please listen carefully.",
  sword: "The knight has a long sword.",
  scene: "It was a funny scene.",
  sign: "Read the stop sign.",

  // common sight words additions
  again: "Try it again, please.",
  always: "I always brush my teeth.",
  another: "Have another bite.",
  around: "Look around the room.",
  before: "Wash your hands before lunch.",
  between: "Sit between us.",
  where: "Where did you put it?",
  above: "The clock is above the door.",
  should: "You should rest now.",
  great: "That's a great idea!",
  right: "You got it right!",
  thought: "I thought it was Friday.",
  together: "We can fix it together.",
  today: "Today is sunny.",
  until: "Wait until I come back.",
  water: "Drink some water.",
  world: "The world is huge.",
  young: "She is a young pup.",
  enough: "You've had enough candy.",
};

interface SpellingItem {
  id: string;
  skillTag: SpellingSkillTag;
  word: string;
  sentence: string;
  difficulty: number;
  hintLadder: string[];
}

/**
 * Build spelling items for a given skill. Deterministic given the seed.
 */
export function generateSpellingItems(
  tag: SpellingSkillTag,
  opts: { count: number; seed?: number }
): SpellingItem[] {
  const pool = SPELLING_WORDS[tag];
  const seed = opts.seed ?? 1;
  // Simple rotation by seed for determinism
  const start = seed % pool.length;
  const out: SpellingItem[] = [];
  const difficulty = SPELLING_SKILLS.find((s) => s.tag === tag)!.difficulty;
  for (let i = 0; i < opts.count; i++) {
    const word = pool[(start + i) % pool.length];
    out.push({
      id: `spell:${tag}:${word}`,
      skillTag: tag,
      word,
      sentence: SPELLING_SENTENCES[word] ?? `Can you spell ${word}?`,
      difficulty,
      hintLadder: [
        `It starts with "${word[0]}".`,
        `It has ${word.length} letters.`,
        `Sound it out slowly.`,
      ],
    });
  }
  return out;
}
